# Generated by Django 4.2.7 on 2023-12-15 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_futbol', models.CharField(choices=[('5', '5'), ('7', '7'), ('11', '11')], default='7', max_length=2)),
                ('cupos_disponibles', models.IntegerField(default=0)),
                ('posiciones_necesarias', models.CharField(choices=[('Arquero', 'Arquero'), ('Defensa', 'Defensa'), ('Medio', 'Medio'), ('Delantero', 'Delantero')], default='Medio', max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL)),
                ('jugadores', models.ManyToManyField(related_name='jugadores', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.ubicacion')),
            ],
        ),
    ]
