# Generated by Django 4.2.7 on 2023-12-21 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='jugadores',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='posiciones_necesarias',
        ),
        migrations.AlterField(
            model_name='partido',
            name='tipo_futbol',
            field=models.CharField(choices=[('5', 'Futbol 5'), ('7', 'Futbol 7'), ('11', 'Futbol 11')], default='7', max_length=2),
        ),
        migrations.CreateModel(
            name='PosicionCupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('Arquero', 'Arquero'), ('Defensa', 'Defensa'), ('Medio', 'Medio'), ('Delantero', 'Delantero')], max_length=100)),
                ('cupos', models.IntegerField(default=1)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidos.partido')),
            ],
        ),
    ]
