# Generated by Django 4.2.7 on 2023-12-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
        ('partidos', '0002_remove_partido_jugadores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicaciones.ubicacion'),
        ),
    ]
