# Generated by Django 5.0.4 on 2024-05-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_partido_cupos_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidojugador',
            name='posicion',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
