# Generated by Django 4.2.7 on 2023-12-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
        ('partidos', '0003_alter_partido_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.ubicacion'),
        ),
    ]
