# Generated by Django 4.2.7 on 2023-12-22 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubicaciones', '0001_initial'),
        ('partidos', '0004_alter_partido_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partido',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicaciones.ubicacion'),
        ),
        migrations.AlterField(
            model_name='posicioncupo',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partidos.partido'),
        ),
    ]
