# Generated by Django 4.2.7 on 2023-12-23 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0006_alter_posicioncupo_partido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicioncupo',
            name='partido',
        ),
        migrations.AddField(
            model_name='partido',
            name='posiciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partidos.posicioncupo'),
        ),
    ]
