# Generated by Django 4.2.7 on 2023-12-23 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partidos', '0007_remove_posicioncupo_partido_partido_posiciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidos.partido')),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='jugadores',
            field=models.ManyToManyField(through='partidos.PartidoJugador', to=settings.AUTH_USER_MODEL),
        ),
    ]
