# Generated by Django 4.2.7 on 2023-12-23 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partidos', '0008_partidojugador_partido_jugadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidojugador',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
