# Generated by Django 4.2.7 on 2024-01-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0009_alter_partidojugador_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'For Femenino'), ('U', 'Mixto')], default='U', max_length=1),
        ),
    ]
