# Generated by Django 4.2.7 on 2023-12-14 11:38

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(default='-74.806981,10.987807', max_length=100)),
            ],
        ),
    ]
