# Generated by Django 4.2.7 on 2023-11-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('equipo', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
    ]
