# Generated by Django 4.2.7 on 2023-11-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='equipo',
        ),
    ]
