# Generated by Django 4.2.7 on 2023-11-26 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0002_remove_jugador_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='edad',
        ),
        migrations.AddField(
            model_name='jugador',
            name='correo',
            field=models.EmailField(default='example@gmail.com', max_length=254, unique=True, verbose_name='correo'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today, verbose_name='fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=50, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(max_length=60, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
    ]
