# Generated by Django 5.0.4 on 2024-05-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0003_alter_jugador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='correo',
            field=models.EmailField(error_messages={'unique': 'Este correo ya esta en uso'}, max_length=254, unique=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='user',
            field=models.CharField(default=' ', error_messages={'unique': 'El nombre de usuario ya esta en uso'}, max_length=50, unique=True, verbose_name='username'),
        ),
    ]
