# Generated by Django 4.2.7 on 2023-12-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0010_alter_jugador_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='correo',
            field=models.EmailField(default='example@gmail.com', max_length=254, unique=True, verbose_name='correo'),
        ),
    ]
