# Generated by Django 4.2.7 on 2023-12-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
        ('jugador', '0011_alter_jugador_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.ubicacion'),
        ),
    ]
