# Generated by Django 4.2.7 on 2024-01-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0013_alter_jugador_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='descripcion',
        ),
    ]
