# Generated by Django 4.2.7 on 2024-01-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0014_remove_jugador_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='user',
            field=models.CharField(default=' ', max_length=50, verbose_name='username'),
        ),
    ]
